runtime: python
env: flex
entrypoint: gunicorn -b :$PORT config.wsgi

beta_settings:
  cloud_sql_instances: effigia-172804:us-central1:effigia-db-2

runtime_config:
  python_version: 2

env_variables:
  DJANGO_ADMIN_PASS: test1234
  DJANGO_DB_NAME: effigia
  DJANGO_DB_USER: postgres
  DJANGO_DB_PASS: rootroot
  DJANGO_DB_HOST: /cloudsql/effigia-172804:us-central1:effigia-db-2
  DJANGO_STATIC_URL: https://storage.googleapis.com/effigia-172804/public/static/
  DJANGO_MEDIA_URL: https://storage.googleapis.com/effigia-172804/public/media/
  
  GOOGLE_OAUTH2_CLIENT_ID: 147769121370-qitjpq9b7o68nh3jn4g7p6k3nkr30vsh.apps.googleusercontent.com
  GOOGLE_OAUTH2_CLIENT_SECRET: UZ_MLeSLzdVnlgPTUmaBY1u0
  
  FACEBOOK_OAUTH2_CLIENT_ID: 271245203283604
  FACEBOOK_OAUTH2_CLIENT_SECRET: 5b9499a28d20de42bf247ff501652b96
  
  TWITTER_OAUTH2_CLIENT_ID: rLXWzi895ag67sVsJQ2jKrtL1
  TWITTER_OAUTH2_CLIENT_SECRET: RJXnlghhkdxtNmujCvoj7dVylL2Nl7Z2XafVJVw3ieoGXMhutZ
